#-----------------------------------------
# GitHub Action CI
#-----------------------------------------
name: createst-ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Установка пакетов
        run: npm install

      - name: Установка пакетов
        run: npm run build
      
