#-----------------------------------------
# GitHub Action CI
#-----------------------------------------
name: createst-ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Print Hello Message
        run: echo "Hello World"
