#-----------------------------------------
# GitHub Action CI
#-----------------------------------------
name: createst-ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Клонирование репозитория
        run: 
      - name: Установка пакетов
        run: npm install
      - name: 
